//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgadriveData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Driver { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public string LicenseNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> Password { get; set; }
    }
}
